import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'FeedMe - Bruk det du har, spar det du kan!',
  description: 'Generated by the greatest of all time',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>FeedMe - Bruk det du har, spar det du kan!</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
